CentOS 8: switch to use centos 8 stream (quay.io/centos/centos:stream8)
CentOS 8 reached EOL on December 31, 2021 (https://www.centos.org/centos-linux-eol/)
Repositories have moved to vault.centos.org, causing builds to fail;

    Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist

Update the Dockerfile to use quay.io/centos/centos:stream8

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>